### ISSUE TITLE
BehaviorLog,y轴异常

### ISSUE THREAD

**Issue by CNDogc** [LiteLScript-Dev/LXL-Plugins#5]
y轴的读取是有问题的，比如放置一个方块，读取的方块是真实方块的下面一个y坐标。比如我在1,64,1放了一个木板,但是日志出来的效果是我在1,63,1放了一个草方块

**Comment by CNDogc** [comment]
BDS 1.19.10 LL 2.4.2 BehaviorLog 最新版本

**Comment by yqs112358** [comment]
坐标问题是LL那边API出的问题，BehaviorLog只是调用LL接口并输出结果。LL应该很早就已修复。
